version: "3"
services:
  datascience:
    build:
      context: ./docker/datascience
    tty: true
    ports:
      - "10190:8888"
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/workspace/datascience
    command:
      jupyter lab --no-browser --ip=0.0.0.0 --allow-root --LabApp.token=''
    volumes:
      - ./data:/workspace/data:cached
      - ./datascience:/workspace/datascience:cached
  pytorch:
    shm_size: "20gb"
    build:
      context: ./docker/pytorch
    tty: true
    ports:
      - "10190:8888"
      - "10107:5000"
    environment:
      - PYTHONPATH=/workspace/pytorch
    volumes:
      - ./data:/workspace/data:cached
      - ./pytorch:/workspace/pytorch:cached
      - ./datascience:/workspace/datascience:ro
      - ./mlruns:/workspace/mlruns:cached
    command: mlflow ui --backend-store-uri /workspace/mlruns --host 0.0.0.0
